services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest
    user: root
    container_name: sqlserver
    hostname: sqlserver
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "sa$password"
    volumes:
      - ./data:/var/opt/mssql
